[context.no-store] 
command = "npm run build && cp ./custom-headers/_noStore ./build/_headers"

[context.no-cache] 
command = "npm run build && cp ./custom-headers/_noCache ./build/_headers"

[context.s-maxage] 
command = "npm run build && cp ./custom-headers/_sMaxAge ./build/_headers"

[context.max-age] 
command = "npm run build && cp ./custom-headers/_maxAge ./build/_headers"

[context.private] 
command = "npm run build && cp ./custom-headers/_private ./build/_headers"

[context.min-fresh] 
command = "npm run build && cp ./custom-headers/_minFresh ./build/_headers"

[context.only-if-cached] 
command = "npm run build && cp ./custom-headers/_onlyIfCached ./build/_headers"

[context.proxyRevalidate] 
command = "npm run build && cp ./custom-headers/_proxyRevalidate ./build/_headers"

[context.stale-if-error] 
command = "npm run build && cp ./custom-headers/_staleIfError ./build/_headers"

[context.stale-while-revalidate] 
command = "npm run build && cp ./custom-headers/_staleWhileRevalidate ./build/_headers"
